# generated by configure on Thu, 17 Apr 2014 11:25:02 -0400
#   options: "--enable-python"

CONF_INSTALL_PREFIX = "/usr/local"
CONF_INSTALL_LIBDIR = "/usr/local/lib"
CONF_SYSINC_SECCOMP = 1
CONF_BINDINGS_PYTHON = 1

