#!/bin/bash

#
# libseccomp credit updater script
#
# Copyright (c) 2017 Red Hat <pmoore@redhat.com>
# Author: Paul Moore <paul@paul-moore.com>
#

#
# This library is free software; you can redistribute it and/or modify it
# under the terms of version 2.1 of the GNU Lesser General Public License as
# published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
# for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, see <http://www.gnu.org/licenses>.
#

# header
echo "libseccomp: Contributors"
echo "========================================================================"
echo "https://github.com/seccomp/libseccomp"
echo ""

# body
git log --pretty=format:"%aN <%aE>" | \
	grep -v '<libseccomp@googlegroups.com>' | \
	sort -u

exit 0
