#!/bin/bash

# NOTE: changes to the arch_syscall_table struct in syscalls.h will affect
#       this script/gperf - BEWARE!

###
# helper functions

function exit_usage() {
	echo "usage: $0 <syscall_csv_file> <gperf_template>"
	exit 1
}

###
# main

# sanity check
[[ ! -r "$1" || ! -r "$2" ]] && exit_usage
sys_csv=$1
gperf_tmpl=$2

sys_csv_tmp=$(mktemp -t generate_syscalls_XXXXXX)

# filter and prepare the syscall csv file
awk -vFS=, -vOFS=, -vn=0 '/^[^#]/ {
  if ($4 != "PNR") { $4 = "0x40000000|"$4; } # x32
  if ($7 != "PNR") { $7 = 4000+$7; }         # mips
  if ($8 != "PNR") { $8 = 5000+$8; }         # mips64
  if ($9 != "PNR") { $9 = 6000+$9; }         # mips64n32
  $2 = n++ OFS $2;
  gsub("PNR", "__PNR_" $1);
  print
}' $sys_csv > $sys_csv_tmp
[[ $? -ne 0 ]] && exit 1

# create the gperf file
sed -e "/@@SYSCALLS_TABLE@@/r $sys_csv_tmp" \
    -e '/@@SYSCALLS_TABLE@@/d' \
    $gperf_tmpl > syscalls.perf
[[ $? -ne 0 ]] && exit 1

# cleanup
rm -f $sys_csv_tmp

exit 0
